name: "Testing"

on:
  push:
    branches: ["main", "dev"]
    paths:
     - 'bilibili_api/**'
     - 'tests/**'
  
  schedule:
    - cron: '0 4 * * 6'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start test
        env:
          BILI_SESSDATA: ${{ secrets.BILI_SESSDATA }}
          BILI_CSRF: ${{ secrets.BILI_CSRF }}
          BILI_RATELIMIT: 0.2
          BILI_BUVID3: ${{ secrets.BILI_BUVID3 }}
        run: "python -m tests.main -a"
